name: Question
description: 提出一个问题
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        在提问之前，请先查阅：
        - [用户手册](https://github.com/YOUR_USERNAME/phantom-stream/blob/main/defender/USER_MANUAL.md)
        - [技术文档](https://github.com/YOUR_USERNAME/phantom-stream/blob/main/defender/README.md)
        - [现有 Issues](https://github.com/YOUR_USERNAME/phantom-stream/issues)

  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 请详细描述您的问题
      placeholder: 我想了解...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 相关背景
      description: 提供一些背景信息
      placeholder: 我正在尝试...

  - type: textarea
    id: tried
    attributes:
      label: 已尝试的方法
      description: 您已经尝试过哪些方法？
      placeholder: 我尝试了...

  - type: textarea
    id: environment
    attributes:
      label: 环境信息（如果相关）
      description: 您的环境信息
      value: |
        - OS: 
        - Go Version: 
        - phantom-guard Version:
      render: markdown
